import { AssessmentState, Criticality, SystemCategory, AssessmentType, AssessmentModule, RiskLevel, AssetType } from '../types';

export const getCoreBankingSampleData = (): Omit<AssessmentState, 'isInitialized'> => {
  return {
    projectName: 'Core Banking Modernization (Temenos T24)',
    systemOwner: 'EVP of Core Systems',
    assetCriticality: Criticality.HIGH,
    businessCriticality: Criticality.HIGH,
    systemCategory: SystemCategory.BANKING,
    assessmentType: AssessmentType.BANKING,
    startDate: new Date().toISOString().split('T')[0],
    systemScope: [
      { ip: '10.50.10.15', hostname: 'T24-APP-01', type: AssetType.SERVER, environment: 'Production', businessCritical: true },
      { ip: '10.50.10.16', hostname: 'T24-APP-02', type: AssetType.SERVER, environment: 'Production', businessCritical: true },
      { ip: '10.50.20.10', hostname: 'ORA-T24-DB-01', type: AssetType.DATABASE, environment: 'Production', businessCritical: true },
      { ip: '10.50.20.11', hostname: 'ORA-T24-DB-02', type: AssetType.DATABASE, environment: 'Production', businessCritical: true },
      { ip: '10.51.10.15', hostname: 'T24-UAT-01', type: AssetType.SERVER, environment: 'UAT', businessCritical: false },
      { ip: '192.168.100.5', hostname: 'WAF-P-01', type: AssetType.NETWORK_DEVICE, environment: 'Production', businessCritical: true, internetFacing: true },
      { ip: 'api.corebanking.internal', hostname: 'T24-API-GW', type: AssetType.API, environment: 'Production', businessCritical: true }
    ],
    moduleScores: {
      [AssessmentModule.ARCHITECTURE]: 72,
      [AssessmentModule.IDENTITY]: 65,
      [AssessmentModule.VULNERABILITY]: 88,
      [AssessmentModule.APPLICATION]: 75,
      [AssessmentModule.DATA]: 60,
      [AssessmentModule.LOGGING]: 90,
      [AssessmentModule.INCIDENT]: 85,
      [AssessmentModule.HARDENING]: 70,
      [AssessmentModule.CLOUD_SECURITY]: 100, // Not applicable or perfect score
      [AssessmentModule.ENDPOINT_SECURITY]: 80,
      [AssessmentModule.EMAIL_SECURITY]: 85,
      [AssessmentModule.SECURITY_OPERATIONS]: 75,
      [AssessmentModule.BUSINESS_CONTINUITY]: 82,
      [AssessmentModule.THIRD_PARTY]: 90,
      [AssessmentModule.GOVERNANCE]: 88,
      [AssessmentModule.OTHER]: 100
    },
    enabledModules: [
      AssessmentModule.ARCHITECTURE,
      AssessmentModule.IDENTITY,
      AssessmentModule.VULNERABILITY,
      AssessmentModule.APPLICATION,
      AssessmentModule.DATA,
      AssessmentModule.LOGGING,
      AssessmentModule.INCIDENT,
      AssessmentModule.HARDENING,
      AssessmentModule.BUSINESS_CONTINUITY,
      AssessmentModule.THIRD_PARTY,
      AssessmentModule.GOVERNANCE
    ],
    findings: [
      {
        id: 'sample-1',
        module: AssessmentModule.IDENTITY,
        title: 'Hardcoded Service Account Credentials in API Gateway',
        riskLevel: RiskLevel.CRITICAL,
        riskScore: 95,
        observation: 'During API review, it was identified that the T24-API-GW uses hardcoded basic authentication credentials to connect to the backend Core Banking system.',
        evidence: 'File: /opt/gateway/conf/routes.xml, Line 45 (Credentials visible in plaintext)',
        impact: 'Compromise of the API Gateway configuration could lead to full unauthorized access to the core banking APIs.',
        likelihood: 'High',
        rootCause: 'Improper secrets management during legacy gateway deployment.',
        recommendation: 'Migrate credentials to the enterprise secret vault (CyberArk/HashiCorp) and implement dynamic credential generation or certificate-based authentication (mTLS).',
        owner: 'API Gateway Admin',
        dueDate: '7 Days',
        status: 'Open',
        frameworks: ['NIST CSF PR.AC-1', 'PCI DSS 8.2.1', 'SWIFT CSP 1.2']
      },
      {
        id: 'sample-2',
        module: AssessmentModule.DATA,
        title: 'Customer PII Unmasked in UAT Environment',
        riskLevel: RiskLevel.HIGH,
        riskScore: 82,
        observation: 'The T24-UAT-01 database contains live customer PII (including Account Numbers and Balances) cloned directly from Production without static data masking.',
        evidence: 'Sample query on UAT database table FBNK_CUSTOMER returned unmasked SSN and personal details.',
        impact: 'Exposure of customer PII to developers and testers increases the risk of insider threat data exfiltration and violates privacy regulations.',
        likelihood: 'Medium',
        rootCause: 'Lack of automated data masking tools within the non-production data refresh pipeline.',
        recommendation: 'Implement a static data masking (SDM) solution to obfuscate sensitive fields during the production-to-UAT database refresh process.',
        owner: 'Data Architecture',
        dueDate: '30 Days',
        status: 'Open',
        frameworks: ['NIST CSF PR.DS-1', 'ISO 27001:A.14.3', 'GDPR Art. 32']
      },
      {
        id: 'sample-3',
        module: AssessmentModule.ARCHITECTURE,
        title: 'Missing Micro-segmentation between Web and App Tiers',
        riskLevel: RiskLevel.HIGH,
        riskScore: 78,
        observation: 'Network traffic is permitted indiscriminately on all ports between the front-end presentation zone and the core application zone.',
        evidence: 'Firewall ruleset review on FW-INT-01 reveals an "ALLOW ANY" rule from VLAN 50 (Web) to VLAN 60 (App).',
        impact: 'If a front-end server is compromised, an attacker can easily pivot and laterally move to the core banking application servers.',
        likelihood: 'Medium',
        rootCause: 'Legacy network deployment relying on perimeter security rather than Zero Trust principles.',
        recommendation: 'Restrict traffic between the Web and App tiers to only require required ports (e.g., TCP 8443) using strict stateful firewall rules.',
        owner: 'Network Security',
        dueDate: '45 Days',
        status: 'In Progress',
        frameworks: ['NIST CSF PR.AC-5', 'CIS v8 12.2', 'PCI DSS 1.2.1']
      },
      {
        id: 'sample-4',
        module: AssessmentModule.HARDENING,
        title: 'Default Configuration on Oracle Database Listener',
        riskLevel: RiskLevel.MEDIUM,
        riskScore: 55,
        observation: 'The Oracle database listeners on ORA-T24-DB-01 and ORA-T24-DB-02 are running with default configurations and allow unauthenticated TNS ping responses.',
        evidence: 'Nmap scan confirmed port 1521 is open and responds to TNSPING without authentication.',
        impact: 'Information disclosure regarding the database version and availability, which aids in targeted attacks.',
        likelihood: 'Low',
        rootCause: 'Standard database build image does not include CIS benchmark hardening for Oracle listeners.',
        recommendation: 'Apply the CIS Oracle Database Benchmark standards. Restrict listener access via valid node checking (tcp.validnode_checking).',
        owner: 'DBA Team',
        dueDate: '90 Days',
        status: 'Open',
        frameworks: ['CIS v8 4.1']
      },
      {
        id: 'sample-5',
        module: AssessmentModule.VULNERABILITY,
        title: 'Outdated Apache Struts Component in Legacy Portal module',
        riskLevel: RiskLevel.HIGH,
        riskScore: 85,
        observation: 'A vulnerability scan identified Apache Struts 2.3.x on T24-APP-01, which is vulnerable to remote code execution (CVE-2017-5638).',
        evidence: 'Tenable Nessus Plugin ID 97737 detected the component.',
        impact: 'RCE could allow full server compromise if the vulnerable endpoint is reachable by an attacker.',
        likelihood: 'High (if exposed) / Low (due to internal WAF)',
        rootCause: 'Delayed application patching due to dependencies in the legacy portal module.',
        recommendation: 'Upgrade Apache Struts to the latest stable version or apply virtual patching on the WAF as an interim control.',
        owner: 'Application Support',
        dueDate: '14 Days',
        status: 'Mitigated',
        frameworks: ['NIST CSF ID.RA-1', 'PCI DSS 6.2']
      }
    ]
  };
};
