import React from 'react';
import { MATURITY_FORMULA, MATURITY_MODEL_VERSION, MATURITY_PROVENANCE, MATURITY_ROUNDING, SUPPORTED_MVP_MODULES } from '../services/assessmentModel';

export const DocumentationTab: React.FC = () => (
  <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div className="border-b border-slate-200 bg-slate-50 p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">Method and limits</p><h2 className="mt-2 text-2xl font-bold text-slate-900">Evidence-led maturity indicator</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">The indicator is transparent and deliberately limited: it summarizes assessor-entered ordinal ratings only after evidence coverage is present.</p></div>
    <div className="space-y-8 p-6 sm:p-8">
      <section><h3 className="text-lg font-bold text-slate-900">Formula and validity</h3><p className="mt-2 text-sm leading-6 text-slate-600">{MATURITY_FORMULA}. Architecture &amp; Network and Vulnerability &amp; Exposure each weigh 50%; each rating is an assessor-entered integer from 0–5. Every component needs at least one eligible finding with complete required fields and evidence reference plus excerpt. Missing or unknown is invalid, not zero. Evidence counts affect eligibility only, never the component value. Model version: <strong>{MATURITY_MODEL_VERSION}</strong>. Provenance: {MATURITY_PROVENANCE} Rounding: {MATURITY_ROUNDING}.</p><div className="mt-4 flex flex-wrap gap-2">{SUPPORTED_MVP_MODULES.map(module => <span key={module} className="rounded-full bg-cyan-50 px-3 py-1.5 text-sm font-semibold text-cyan-950 ring-1 ring-inset ring-cyan-200">{module} · 50%</span>)}</div></section>
      <section className="rounded-xl border border-cyan-200 bg-cyan-50 p-5"><h3 className="text-lg font-bold text-cyan-950">Local evidence helper</h3><p className="mt-2 text-sm leading-6 text-cyan-950">Supported lexical text formats are parsed locally only, within 1 MB and 2,000 lines; JSON is additionally checked for malformed syntax. The helper returns excerpts and line locators; it never uploads, transmits, scans, infers findings, assigns severity, or validates controls. Verify copied excerpts against the source.</p></section>
      <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h3 className="text-lg font-bold text-amber-950">Explicit limits</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-amber-950"><li>• The indicator is not risk, posture, compliance, assurance, or control effectiveness.</li><li>• Unsupported modules are not assessed, passed, or failed.</li><li>• Binary, encrypted, malformed, and semantically complex files are outside the parser boundary.</li><li>• Qualified human review and source retention remain required.</li></ul></section>
      <section><h3 className="text-lg font-bold text-slate-900">Responsible use</h3><p className="mt-2 text-sm leading-6 text-slate-600">Use only authorized evidence. Review each finding against its referenced source and obtain qualified review before relying on any conclusion.</p></section>
    </div>
  </div>
);
